# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Waterfurnace-Aurora"
  org.opencontainers.image.description: "Add-on that run the waterfurnace-aurora service to interface with your geothermal heatpump."
  org.opencontainers.image.source: "https://github.com/mdallaire/hass-addon-waterfurnace-aurora"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
